#!/usr/bin/env bash
# Summary: List hook scripts for a given scalaenv command
# Usage: scalaenv hooks <command>

set -e
test -n "$SCALAENV_DEBUG" && set -x

# Provide scalaenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo which
  exit
fi

SCALAENV_COMMAND="$1"
if [ -z "$SCALAENV_COMMAND" ]; then
  scalaenv-help --usage hooks >& 2
  exit 1
fi

if ! enable -f "${BASH_SOURCE%/*}"/scalaenv-realpath.dylib realpath 2>/dev/null; then
  if [ -n "$SCALAENV_NATIVE_EXT" ]; then
    echo "scalaenv: failed to load \`realpath' builtin" >&2
    exit 1
  fi
fi
READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "scalaenv: cannot find readlink - are you missing GNU coreutils?" >& 2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

realpath() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  echo "$(pwd)/${name}"
  cd "$cwd"
}

IFS=: hook_paths=($SCALAENV_HOOK_PATH)

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$SCALAENV_COMMAND"/*.bash; do
    echo $(realpath $script)
  done
done
shopt -u nullglob
