#!/usr/bin/env bash
set -e
test -n "${SCALAENV_DEBUG}" && set -x

# Provide scalaenv completions
if [ "${1}" = "--complete" ]; then
  exec scalaenv-rehash --complete
fi

shell="$(basename "${SCALAENV_SHELL:-${SHELL}}")"

# When scalaenv shell integration is enabled, delegate to scalaenv-rehash,
# then tell the shell to empty its command lookup cache.
scalaenv-rehash

case "${shell}" in
* )
  echo "hash -r 2> /dev/null || true"
  ;;
esac
