#!/usr/bin/env bash
# Summary: List all available scalaenv commands
# Usage: scalaenv commands [--sh|--no-sh]

set -e
test -n "${SCALAENV_DEBUG}" && set -x

COMMAND="${1}"
if [ -z "${COMMAND}" ]; then
  scalaenv-help --usage completions >& 2
  exit 1
fi

# Provide scalaenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec scalaenv-commands
fi


COMMAND_PATH="$(command -v "scalaenv-${COMMAND}" || command -v "scalaenv-sh-${COMMAND}")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide scalaenv completions" "${COMMAND_PATH}" > /dev/null; then
  shift
  exec "${COMMAND_PATH}" --complete "${@}"
fi
