#!/usr/bin/env bash
# Summary: Show the current Scala version

set -e
test -n "${SCALAENV_DEBUG}" && set -x

if [ -z "${SCALAENV_VERSION}" ]; then
  SCALAENV_VERSION_FILE="$(scalaenv-version-file)"
  SCALAENV_VERSION="$(scalaenv-version-file-read "${SCALAENV_VERSION_FILE}" || true)"
fi

if [ -z "${SCALAENV_VERSION}" ] || [ "${SCALAENV_VERSION}" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="${1}"
  test -d "${SCALAENV_ROOT}/versions/${version}"
}

if version_exists "${SCALAENV_VERSION}"; then
  echo "${SCALAENV_VERSION}"
elif version_exists "${SCALAENV_VERSION#scala-}"; then
  { echo "warning: ignoring extraneous \`scala-\` prefix in version \`${SCALAENV_VERSION}\`"
    echo "         (set by $(scalaenv-version-origin))"
  } >& 2
  echo "${SCALAENV_VERSION#ruby-}"
else
  echo "scalaenv: version \`${SCALAENV_VERSION}\` is not installed" >& 2
  exit 1
fi

